version: '3.8'
services:
  postgres-db:
    image: postgres:16
    container_name: einblick-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: einblick
      POSTGRES_USER: einblick
      POSTGRES_PASSWORD: einblick1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Backend/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U einblick -d einblick"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
