-- ============================================================
-- einblick WMS - Phase 1 DB 스키마 (PostgreSQL)
-- Oracle 23ai 스키마(einblick_schema_oracle.sql)에서 마이그레이션됨
-- ============================================================

CREATE TABLE users (
                       user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name            VARCHAR(50)  NOT NULL,
                       login_id        VARCHAR(50)  NOT NULL UNIQUE,
                       password        VARCHAR(255) NOT NULL,
                       role            VARCHAR(20) DEFAULT 'STAFF' NOT NULL
                           CHECK (role IN ('STAFF','MANAGER','DIRECTOR','ADMIN')),
                       brand_scope     VARCHAR(200),
                       approval_level  INTEGER DEFAULT 0,
                       created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE customers (
                           customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           code            VARCHAR(30) NOT NULL UNIQUE,
                           name            VARCHAR(100) NOT NULL,
                           is_house_alias  BOOLEAN DEFAULT FALSE NOT NULL,
                           packing_method  VARCHAR(60),
                           format          VARCHAR(100),
                           assort_solid    VARCHAR(30),
                           std_ratio       VARCHAR(50),
                           std_polybag     VARCHAR(20),
                           std_carton      VARCHAR(20),
                           std_hanger      VARCHAR(300),
                           created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE programs (
                          program_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          brand           VARCHAR(50) NOT NULL,
                          league          VARCHAR(50),
                          style_code      VARCHAR(50) NOT NULL,
                          style_name      VARCHAR(200),
                          season          VARCHAR(30),
                          created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CONSTRAINT uq_program_style_season UNIQUE (style_code, season)
);

CREATE TABLE purchase_orders (
                                 po_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 po_number        VARCHAR(30) NOT NULL UNIQUE,
                                 program_id       BIGINT NOT NULL,
                                 customer_id      BIGINT NOT NULL,
                                 dlvy_date        DATE,
                                 transport_method VARCHAR(20) DEFAULT 'UNASSIGNED' NOT NULL
                                     CHECK (transport_method IN ('AIR','BOAT','SPLIT','UNASSIGNED')),
                                 status           VARCHAR(20) DEFAULT 'RECEIVED' NOT NULL
                                     CHECK (status IN ('RECEIVED','IN_REVIEW','RECONCILED','MISMATCH','SHIPPED','CLOSED')),
                                 original_pdf_url VARCHAR(500),
                                 total_qty        INTEGER DEFAULT 0 NOT NULL,
                                 created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 CONSTRAINT fk_po_program  FOREIGN KEY (program_id)  REFERENCES programs(program_id),
                                 CONSTRAINT fk_po_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE po_history (
                            history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            po_id           BIGINT NOT NULL,
                            user_id         BIGINT NOT NULL,
                            field_changed   VARCHAR(50),
                            old_value       VARCHAR(200),
                            new_value       VARCHAR(200),
                            comment         VARCHAR(500),
                            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            CONSTRAINT fk_pohist_po   FOREIGN KEY (po_id)   REFERENCES purchase_orders(po_id),
                            CONSTRAINT fk_pohist_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE po_lines (
                          po_line_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          po_id           BIGINT NOT NULL,
                          team            VARCHAR(100),
                          player          VARCHAR(100),
                          total_qty       INTEGER DEFAULT 0 NOT NULL,
                          carton_qty      INTEGER,
                          CONSTRAINT fk_poline_po FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id)
);

CREATE TABLE po_line_sizes (
                               po_line_size_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               po_line_id      BIGINT NOT NULL,
                               size_code       VARCHAR(10) NOT NULL,
                               qty             INTEGER DEFAULT 0 NOT NULL,
                               CONSTRAINT fk_polinesize_line FOREIGN KEY (po_line_id) REFERENCES po_lines(po_line_id),
                               CONSTRAINT uq_poline_size UNIQUE (po_line_id, size_code)
);

CREATE TABLE assorts (
                         assort_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         program_id      BIGINT NOT NULL,
                         team            VARCHAR(100),
                         player          VARCHAR(100),
                         customer_label  VARCHAR(50) NOT NULL,
                         assort_solid    VARCHAR(30),
                         ratio           VARCHAR(50),
                         polybag         VARCHAR(20),
                         carton          VARCHAR(20),
                         hanger          VARCHAR(300),
                         total_qty       INTEGER DEFAULT 0 NOT NULL,
                         source_file     VARCHAR(300),
                         created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT fk_assort_program FOREIGN KEY (program_id) REFERENCES programs(program_id)
);

CREATE TABLE assort_sizes (
                              assort_size_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              assort_id       BIGINT NOT NULL,
                              size_code       VARCHAR(10) NOT NULL,
                              qty             INTEGER DEFAULT 0 NOT NULL,
                              CONSTRAINT fk_assortsize_assort FOREIGN KEY (assort_id) REFERENCES assorts(assort_id),
                              CONSTRAINT uq_assort_size UNIQUE (assort_id, size_code)
);

CREATE TABLE reconciliation_results (
                                        reconciliation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        po_line_id       BIGINT,
                                        assort_id        BIGINT,
                                        diff_qty         INTEGER DEFAULT 0 NOT NULL,
                                        status           VARCHAR(20) NOT NULL
                                            CHECK (status IN ('OK','MISSING_IN_ASSORT','MISSING_IN_PO','QTY_MISMATCH','NEEDS_REVIEW')),
                                        is_house_matched BOOLEAN DEFAULT FALSE NOT NULL,
                                        note             VARCHAR(500),
                                        checked_by       BIGINT,
                                        checked_at       TIMESTAMP,
                                        created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                        CONSTRAINT fk_recon_poline FOREIGN KEY (po_line_id) REFERENCES po_lines(po_line_id),
                                        CONSTRAINT fk_recon_assort FOREIGN KEY (assort_id)  REFERENCES assorts(assort_id),
                                        CONSTRAINT fk_recon_user   FOREIGN KEY (checked_by) REFERENCES users(user_id)
);

-- ============================================================
-- Phase 2~4용 최소 테이블
-- ============================================================

CREATE TABLE samples (
                         sample_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         program_id      BIGINT NOT NULL,
                         type            VARCHAR(20) NOT NULL
                             CHECK (type IN ('SMS','FIT','APPROVAL','TOP','GB_TEST','WALMART_TEST','CNS_TEST')),
                         status           VARCHAR(20) DEFAULT 'PREPARING' NOT NULL
                             CHECK (status IN ('PREPARING','SENT','COMMENT_WAIT','APPROVED','FAIL')),
                         comment_source  VARCHAR(50),
                         due_date        DATE,
                         created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT fk_sample_program FOREIGN KEY (program_id) REFERENCES programs(program_id)
);

CREATE TABLE vendors (
                         vendor_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name            VARCHAR(100) NOT NULL,
                         is_overseas     BOOLEAN DEFAULT FALSE NOT NULL,
                         contact_name    VARCHAR(50),
                         contact_info    VARCHAR(200)
);

CREATE TABLE material_orders (
                                 material_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 program_id       BIGINT NOT NULL,
                                 vendor_id        BIGINT NOT NULL,
                                 item             VARCHAR(200),
                                 qty              INTEGER,
                                 amount           NUMERIC(14,2),
                                 approval_status  VARCHAR(20) DEFAULT 'DRAFT' NOT NULL
                                     CHECK (approval_status IN ('DRAFT','MANAGER_REVIEW','DIRECTOR_REVIEW','APPROVED','REJECTED')),
                                 wire_status      VARCHAR(20) DEFAULT 'NOT_SENT' NOT NULL
                                     CHECK (wire_status IN ('NOT_SENT','WIRED','CONFIRMED')),
                                 transport_method VARCHAR(20) CHECK (transport_method IN ('AIR','BOAT','FEDEX')),
                                 created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 CONSTRAINT fk_matorder_program FOREIGN KEY (program_id) REFERENCES programs(program_id),
                                 CONSTRAINT fk_matorder_vendor  FOREIGN KEY (vendor_id)  REFERENCES vendors(vendor_id)
);

CREATE TABLE packing_methods (
                                 packing_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 customer_id      BIGINT NOT NULL,
                                 ppk_type         VARCHAR(10) NOT NULL CHECK (ppk_type IN ('SOLID','ASSORT')),
                                 ratio            VARCHAR(50),
                                 sticker_types    VARCHAR(100),
                                 CONSTRAINT fk_packing_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE sticker_requests (
                                  sticker_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  po_id            BIGINT NOT NULL,
                                  sticker_type     VARCHAR(10) NOT NULL CHECK (sticker_type IN ('UPC','PRN','LPN')),
                                  qty              INTEGER,
                                  loss_rate        NUMERIC(4,2) DEFAULT 1.00,
                                  status           VARCHAR(20) DEFAULT 'REQUESTED' NOT NULL
                                      CHECK (status IN ('REQUESTED','SENT_TO_FACTORY','CONFIRMED')),
                                  CONSTRAINT fk_sticker_po FOREIGN KEY (po_id) REFERENCES purchase_orders(po_id)
);

CREATE TABLE shipping_rules (
                                shipping_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                program_id       BIGINT NOT NULL,
                                season           VARCHAR(30),
                                po_range_from    VARCHAR(30),
                                po_range_to      VARCHAR(30),
                                transport_method VARCHAR(20) NOT NULL CHECK (transport_method IN ('AIR_ONLY','BOAT_ONLY','SPLIT')),
                                ex_factory_date  DATE,
                                CONSTRAINT fk_shiprule_program FOREIGN KEY (program_id) REFERENCES programs(program_id)
);

-- TECH PACK / ARTWORK 파일 관리 (파일 본문은 BYTEA로 DB에 직접 저장)
CREATE TABLE tech_pack_files (
                                  file_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  program_id   BIGINT NOT NULL,
                                  file_name    VARCHAR(255) NOT NULL,
                                  file_type    VARCHAR(20) NOT NULL CHECK (file_type IN ('TECH_PACK','ARTWORK')),
                                  content_type VARCHAR(100),
                                  file_size    BIGINT NOT NULL,
                                  file_data    BYTEA NOT NULL,
                                  status       VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS'
                                      CHECK (status IN ('IN_PROGRESS','IN_REVIEW','APPROVED')),
                                  uploaded_by  BIGINT,
                                  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT fk_techpack_program FOREIGN KEY (program_id) REFERENCES programs(program_id),
                                  CONSTRAINT fk_techpack_user FOREIGN KEY (uploaded_by) REFERENCES users(user_id)
);

-- ---------------------------------
-- 인덱스
-- ---------------------------------
CREATE INDEX idx_po_status      ON purchase_orders(status);
CREATE INDEX idx_po_customer    ON purchase_orders(customer_id);
CREATE INDEX idx_po_program     ON purchase_orders(program_id);
CREATE INDEX idx_recon_status   ON reconciliation_results(status);
CREATE INDEX idx_assort_program ON assorts(program_id);

-- ---------------------------------
-- updated_at 자동갱신 트리거
-- ---------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_po_updated_at
    BEFORE UPDATE ON purchase_orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_techpack_updated_at
    BEFORE UPDATE ON tech_pack_files
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 마이그레이션: PO/ASSORT 대사 고도화 (고객사 패킹정보 마스터 + ASSORT 패킹정보 컬럼)
-- 이미 배포된 DB(예: Railway)에는 위 CREATE TABLE이 다시 실행되지 않으므로,
-- 기존 customers/assorts 테이블에는 아래 ALTER TABLE을 별도로 실행해야 한다.
-- ============================================================
ALTER TABLE customers ADD COLUMN IF NOT EXISTS packing_method VARCHAR(60);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS format         VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS assort_solid   VARCHAR(30);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS std_ratio      VARCHAR(50);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS std_polybag    VARCHAR(20);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS std_carton     VARCHAR(20);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS std_hanger     VARCHAR(300);

ALTER TABLE assorts ADD COLUMN IF NOT EXISTS assort_solid VARCHAR(30);
ALTER TABLE assorts ADD COLUMN IF NOT EXISTS ratio        VARCHAR(50);
ALTER TABLE assorts ADD COLUMN IF NOT EXISTS polybag      VARCHAR(20);
ALTER TABLE assorts ADD COLUMN IF NOT EXISTS carton       VARCHAR(20);
ALTER TABLE assorts ADD COLUMN IF NOT EXISTS hanger       VARCHAR(300);
